CREATE OR REPLACE PROCEDURE REP.SP_PSYIELD_DEFECT_LOG_AGG_TBL_BATCH()
RETURNS INTEGER
LANGUAGE NZPLSQL AS
BEGIN_PROC
	DECLARE 
		pExistFlag boolean;
		pTableName varchar;
		pTableSchema varchar;
		pBatchDefectLogAggView varchar;
	
	BEGIN
		BEGIN AUTOCOMMIT ON
			
			pTableName := 'PSYIELD_DEFECT_LOG_AGG_TMP';
			pTableSchema := 'REP';
			
			pBatchDefectLogAggView := '
										SELECT 
											DEFECT_LOT.SITE_KEY
											,DEFECT_LOT.SITE_CODE
											,DEFECT_LOT.IS_TEST_LOT_ID_FLAG
											,DEFECT_LOT.M_LH_OWNER
											,DEFECT_LOT.M_LH_TRANSACTION_NAME
											,DEFECT_LOT.M_LH_DELETED_FLAG
											,DEFECT_LOT.M_LH_GROUP_FLAG
											,DEFECT_LOT.M_LH_OLD_ROUTE_NAME
											,DEFECT_LOT.M_LH_OLD_ROUTE_NAME_REWORK_SUFFIX
											,DEFECT_LOT.M_LH_OLD_PRODUCT_KEY
											,DEFECT_LOT.M_LH_OLD_PRODUCT_NAME
											,DEFECT_LOT.M_LH_OLD_PROGRAM_KEY
											,DEFECT_LOT.M_LH_OLD_PROGRAM_NAME
											,DEFECT_LOT.M_LH_OLD_PROGRAM_WITH_PN_SUFFIX_FLAG
											,DEFECT_LOT.M_LH_OLD_FACILITY
											,DEFECT_LOT.M_LH_OLD_OPERATION_NAME
											,DEFECT_LOT.M_LH_OPERATION_DATE
											,DEFECT_LOT.M_LH_OPERATION_YEAR
											,DEFECT_LOT.M_LH_OPERATION_QUARTER
											,DEFECT_LOT.M_LH_OPERATION_WEEK
											,DEFECT_LOT.DEFECT_CODE 
											,SUM(DEFECT_LOT.DEFECT_QUANTITY) SUM_DEFECT 
										FROM REP.PSYIELD_DEFECT_LOG_DENORM DEFECT_LOT
										WHERE DEFECT_LOT.M_LH_DELETED_FLAG = ''N'' and DEFECT_LOT.M_LH_GROUP_FLAG = ''N''
										GROUP BY
											DEFECT_LOT.SITE_KEY
											,DEFECT_LOT.SITE_CODE
											,DEFECT_LOT.IS_TEST_LOT_ID_FLAG
											,DEFECT_LOT.M_LH_OWNER
											,DEFECT_LOT.M_LH_TRANSACTION_NAME
											,DEFECT_LOT.M_LH_DELETED_FLAG
											,DEFECT_LOT.M_LH_GROUP_FLAG
											,DEFECT_LOT.M_LH_OLD_ROUTE_NAME
											,DEFECT_LOT.M_LH_OLD_ROUTE_NAME_REWORK_SUFFIX
											,DEFECT_LOT.M_LH_OLD_PRODUCT_KEY
											,DEFECT_LOT.M_LH_OLD_PRODUCT_NAME
											,DEFECT_LOT.M_LH_OLD_PROGRAM_KEY
											,DEFECT_LOT.M_LH_OLD_PROGRAM_NAME
											,DEFECT_LOT.M_LH_OLD_PROGRAM_WITH_PN_SUFFIX_FLAG
											,DEFECT_LOT.M_LH_OLD_FACILITY
											,DEFECT_LOT.M_LH_OLD_OPERATION_NAME
											,DEFECT_LOT.M_LH_OPERATION_DATE
											,DEFECT_LOT.M_LH_OPERATION_YEAR
											,DEFECT_LOT.M_LH_OPERATION_QUARTER
											,DEFECT_LOT.M_LH_OPERATION_WEEK
											,DEFECT_LOT.DEFECT_CODE 
			';
			
			--	RAISE NOTICE 'pBatchDefectLogAggView=%', pBatchDefectLogAggView;
			
			SELECT CASE WHEN COUNT(1) >=1 THEN TRUE ELSE FALSE END INTO pExistFlag FROM _V_TABLE WHERE TABLENAME = pTableName AND SCHEMA = pTableSchema;
			
			IF pExistFlag  = TRUE THEN
				EXECUTE IMMEDIATE 'DROP TABLE ' || pTableSchema || '.'||pTableName;
				RAISE NOTICE 'Table %.% exist, deleted.', pTableSchema, pTableName;
			END IF;
			
			EXECUTE IMMEDIATE 'CREATE TABLE '|| pTableSchema || '.'||pTableName ||' AS SELECT * FROM ( ' || pBatchDefectLogAggView || ' ) t DISTRIBUTE ON (SITE_CODE , M_LH_OLD_PROGRAM_NAME)';
			RAISE NOTICE 'create Table %.%', pTableSchema, pTableName;
		
		END;

	END;
END_PROC;

