EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_LOT_HIS_DENORM_TMP', 'PSYIELD_LOT_HIS_DENORM', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_LOT_HIS_AGG_TMP', 'PSYIELD_LOT_HIS_AGG', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_DEFECT_LOG_DENORM_TMP', 'PSYIELD_DEFECT_LOG_DENORM', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_DEFECT_LOG_AGG_TMP', 'PSYIELD_DEFECT_LOG_AGG', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_DEFECT_CAUSE_SPC_DENORM_TMP', 'PSYIELD_DEFECT_CAUSE_SPC_DENORM', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_DEFECT_CAUSE_LAP_DENORM_TMP', 'PSYIELD_DEFECT_CAUSE_LAP_DENORM', 'REP', 'REP');

EXECUTE SP_TMP_TABLE_REPLACE('PSYIELD_DEFECT_DETAIL_DENORM_TMP', 'PSYIELD_DEFECT_DETAIL_DENORM', 'REP', 'REP');

